INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('714', 'Khoa học giáo dục và đào tạo giáo viên');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('71401', 'Khoa học giáo dục');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140101', 'Giáo dục học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140114', 'Quản lý giáo dục');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('71402', 'Đào tạo giáo viên');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140201', 'Giáo dục Mầm non');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140202', 'Giáo dục Tiểu học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140203', 'Giáo dục Đặc biệt');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140204', 'Giáo dục Công dân');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140205', 'Giáo dục Chính trị');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140206', 'Giáo dục Thể chất');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140207', 'Huấn luyện thể thao');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140208', 'Giáo dục Quốc phòng - An ninh');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140209', 'Sư phạm Toán học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140210', 'Sư phạm Tin học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140211', 'Sư phạm Vật lý');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140212', 'Sư phạm Hoá học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140213', 'Sư phạm Sinh học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140214', 'Sư phạm Kỹ thuật công nghiệp');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140215', 'Sư phạm Kỹ thuật nông nghiệp');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140217', 'Sư phạm Ngữ văn');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140218', 'Sư phạm Lịch sử');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140219', 'Sư phạm Địa lý');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140221', 'Sư phạm Âm nhạc');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140222', 'Sư phạm Mỹ thuật');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140223', 'Sư phạm Tiếng Bana');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140224', 'Sư phạm Tiếng Êđê');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140225', 'Sư phạm Tiếng Jrai');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140226', 'Sư phạm Tiếng Khmer');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140227', 'Sư phạm Tiếng H''mong');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140228', 'Sư phạm Tiếng Chăm');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140229', 'Sư phạm Tiếng M''nông');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140230', 'Sư phạm Tiếng Xê đăng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140231', 'Sư phạm Tiếng Anh');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140232', 'Sư phạm Tiếng Nga');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140233', 'Sư phạm Tiếng Pháp');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140234', 'Sư phạm Tiếng Trung Quốc');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140235', 'Sư phạm Tiếng Đức');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140236', 'Sư phạm Tiếng Nhật');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140237', 'Sư phạm Tiếng Hàn Quốc');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140245', 'Sư phạm nghệ thuật');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140246', 'Sư phạm công nghệ');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140247', 'Sư phạm khoa học tự nhiên');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7140248', 'Giáo dục pháp luật');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('71490', 'Khác');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('721', 'Nghệ thuật');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('72101', 'Mỹ thuật');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7210101', 'Lý luận, lịch sử và phê bình mỹ thuật');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7210103', 'Hội hoạ');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7210104', 'Đồ hoạ');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7210105', 'Điêu khắc');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7210107', 'Gốm');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7210110', 'Mỹ thuật đô thị');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('72102', 'Nghệ thuật trình diễn');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7210201', 'Âm nhạc học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7210203', 'Sáng tác âm nhạc');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7210204', 'Chỉ huy âm nhạc');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7210205', 'Thanh nhạc');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7210207', 'Biểu diễn nhạc cụ phương tây');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7210208', 'Piano');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7210209', 'Nhạc Jazz');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7210210', 'Biểu diễn nhạc cụ truyền thống');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7210221', 'Lý luận, lịch sử và phê bình sân khấu');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7210225', 'Biên kịch sân khấu');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7210226', 'Diễn viên sân khấu kịch hát');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7210227', 'Đạo diễn sân khấu');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7210231', 'Lý luận, lịch sử và phê bình điện ảnh, truyền hình');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7210233', 'Biên kịch điện ảnh, truyền hình');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7210234', 'Diễn viên kịch, điện ảnh - truyền hình');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7210235', 'Đạo diễn điện ảnh, truyền hình');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7210236', 'Quay phim');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7210241', 'Lý luận, lịch sử và phê bình múa');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7210242', 'Diễn viên múa');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7210243', 'Biên đạo múa');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7210244', 'Huấn luyện múa');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('72103', 'Nghệ thuật nghe nhìn');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7210301', 'Nhiếp ảnh');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7210302', 'Công nghệ điện ảnh, truyền hình');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7210303', 'Thiết kế âm thanh, ánh sáng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('72104', 'Mỹ thuật ứng dụng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7210402', 'Thiết kế công nghiệp');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7210403', 'Thiết kế đồ họa');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7210404', 'Thiết kế thời trang');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7210406', 'Thiết kế mỹ thuật sân khấu, điện ảnh');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('72190', 'Khác');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('722', 'Nhân văn');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('72201', 'Ngôn ngữ, văn học và văn hoá Việt Nam');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7220101', 'Tiếng Việt và văn hoá Việt Nam');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7220104', 'Hán Nôm');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7220105', 'Ngôn ngữ Jrai');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7220106', 'Ngôn ngữ Khmer');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7220107', 'Ngôn ngữ H''mong');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7220108', 'Ngôn ngữ Chăm');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7220110', 'Sáng tác văn học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7220112', 'Văn hoá các dân tộc thiểu số Việt Nam');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('72202', 'Ngôn ngữ, văn học và văn hoá nước ngoài');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7220201', 'Ngôn ngữ Anh');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7220202', 'Ngôn ngữ Nga');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7220203', 'Ngôn ngữ Pháp');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7220204', 'Ngôn ngữ Trung Quốc');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7220205', 'Ngôn ngữ Đức');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7220206', 'Ngôn ngữ Tây Ban Nha');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7220207', 'Ngôn ngữ Bồ Đào Nha');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7220208', 'Ngôn ngữ Italia');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7220209', 'Ngôn ngữ Nhật');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7220210', 'Ngôn ngữ Hàn Quốc');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7220211', 'Ngôn ngữ Ảrập');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('72290', 'Khác');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7229001', 'Triết học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('729008', 'Chủ nghĩa xã hội khoa học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7229009', 'Tôn giáo học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7229010', 'Lịch sử');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7229020', 'Ngôn ngữ học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7229030', 'Văn học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7229040', 'Văn hoá học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7229042', 'Quản lý văn hoá');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7229045', 'Gia đình học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('731', 'Khoa học xã hội và hành vi');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('73101', 'Kinh tế học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7310101', 'Kinh tế');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7310102', 'Kinh tế chính trị');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7310104', 'Kinh tế đầu tư');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7310105', 'Kinh tế phát triển');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7310106', 'Kinh tế quốc tế');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7310107', 'Thống kê kinh tế');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7310108', 'Toán kinh tế');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('73102', 'Khoa học chính trị');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7310201', 'Chính trị học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7310202', 'Xây dựng Đảng và chính quyền nhà nước');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7310205', 'Quản lý nhà nước');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7310206', 'Quan hệ quốc tế');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('73103', 'Xã hội học và Nhân học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7310301', 'Xã hội học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7310302', 'Nhân học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('73104', 'Tâm lý học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7310401', 'Tâm lý học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7310403', 'Tâm lý học giáo dục');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('73105', 'Địa lý học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7310501', 'Địa lý học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('73106', 'Khu vực học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7310601', 'Quốc tế học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7310602', 'Châu Á học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7310607', 'Thái Bình Dương học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7310608', 'Đông phương học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7310612', 'Trung Quốc học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7310613', 'Nhật Bản học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7310614', 'Hàn Quốc học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7310620', 'Đông Nam Á học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7310630', 'Việt Nam học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('73190', 'Khác');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('732', 'Báo chí và thông tin');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('73201', 'Báo chí và truyền thông');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7320101', 'Báo chí');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7320104', 'Truyền thông đa phương tiện');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7320105', 'Truyền thông đại chúng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7320106', 'Công nghệ truyền thông');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7320107', 'Truyền thông quốc tế');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7320108', 'Quan hệ công chúng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('73202', 'Thông tin - Thư viện');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7320201', 'Thông tin - thư viện');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7320205', 'Quản lý thông tin');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('73203', 'Văn thư - Lưu trữ - Bảo tàng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7320303', 'Lưu trữ học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7320305', 'Bảo tàng học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('73204', 'Xuất bản - Phát hành');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7320401', 'Xuất bản');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7320402', 'Kinh doanh xuất bản phẩm');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('73290', 'Khác');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('734', 'Kinh doanh và quản lý');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('73401', 'Kinh doanh');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7340101', 'Quản trị kinh doanh');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7340115', 'Marketing');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7340116', 'Bất động sản');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7340120', 'Kinh doanh quốc tế');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7340121', 'Kinh doanh thương mại');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7340122', 'Thương mại điện tử');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7340123', 'Kinh doanh thời trang và dệt may');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('73402', 'Tài chính – Ngân hàng – Bảo hiểm');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7340201', 'Tài chính – Ngân hàng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7340204', 'Bảo hiểm');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('73403', 'Kế toán – Kiểm toán');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7340301', 'Kế toán');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7340302', 'Kiểm toán');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('73404', 'Quản trị – Quản lý');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7340401', 'Khoa học quản lý');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7340403', 'Quản lý công');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7340404', 'Quản trị nhân lực');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7340405', 'Hệ thống thông tin quản lý');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7340406', 'Quản trị văn phòng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7340408', 'Quan hệ lao động');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7340409', 'Quản lý dự  án');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('73490', 'Khác');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('738', 'Pháp luật');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('73801', 'Luật');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7380101', 'Luật');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7380102', 'Luật hiến pháp và luật hành chính');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7380103', 'Luật dân sự và tố tụng dân sự');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7380104', 'Luật hình sự và tố tụng hình sự');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7380107', 'Luật kinh tế');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7380108', 'Luật quốc tế');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('73890', 'Khác');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('742', 'Khoa học sự sống');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('74201', 'Sinh học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7420101', 'Sinh học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('74202', 'Sinh học ứng dụng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7420201', 'Công nghệ sinh học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7420202', 'Kỹ thuật sinh học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7420203', 'Sinh học ứng dụng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('74290', 'Khác');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('744', 'Khoa học tự nhiên');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('74401', 'Khoa học vật chất');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7440101', 'Thiên văn học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7440102', 'Vật lý học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7440106', 'Vật lý nguyên tử và hạt nhân');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7440110', 'Cơ học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7440112', 'Hoá học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7440122', 'Khoa học vật liệu');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('74402', 'Khoa học trái đất');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7440201', 'Địa chất học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7440212', 'Bản đồ học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7440217', 'Địa lý tự nhiênkỹ thuật');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7440221', 'Khí tượng và khí hậu học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7440224', 'Thuỷ văn học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7440228', 'Hải dương học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('74403', 'Khoa học môi trường');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7440301', 'Khoa học môi trường');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('74490', 'Khác');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('746', 'Toán và thống kê');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('74601', 'Toán học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7460101', 'Toán học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7460107', 'Khoa học tính toán');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7460112', 'Toán ứng dụng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7460115', 'Toán cơ');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7460117', 'Toán tin');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('74602', 'Thống kê');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7460201', 'Thống kê');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('74690', 'Khác');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('748', 'Máy tính và công nghệ thông tin');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('74801', 'Máy tính');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7480101', 'Khoa học máy tính');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7480102', 'Mạng máy tính và truyền thông dữ liệu');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7480103', 'Kỹ thuật phần mềm');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7480104', 'Hệ thống thông tin');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7480106', 'Kỹ thuật máy tính');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7480108', 'Công nghệ kỹ thuật máy tính');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('74802', 'Công nghệ thông tin');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7480201', 'Công nghệ thông tin');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7480202', 'An toàn thông tin');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('74890', 'Khác');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('751', 'Công nghệ kỹ thuật');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('75101', 'Công nghệ kỹ thuật kiến trúc và công trình xây dựng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7510101', 'Công nghệ kỹ thuật kiến trúc');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7510102', 'Công nghệ kỹ thuật công trình xây dựng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7510103', 'Công nghệ kỹ thuật xây dựng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7510104', 'Công nghệ kỹ thuật giao thông');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7510105', 'Công nghệ kỹ thuật vật liệu xây dựng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('75102', 'Công nghệ kỹ thuật cơ khí');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7510201', 'Công nghệ kỹ thuật cơ khí');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7510202', 'Công nghệ chế tạo máy');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7510203', 'Công nghệ kỹ thuật cơ điện tử');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7510205', 'Công nghệ kỹ thuật ô tô');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7510206', 'Công nghệ kỹ thuật nhiệt');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7510207', 'Công nghệ kỹ thuật tàu thủy');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7510211', 'Bảo dưỡng công nghiệp');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('75103', 'Công nghệ kỹ thuật điện, điện tử và viễn thông');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7510301', 'Công nghệ kỹ thuật điện, điện tử');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7510302', 'Công nghệ kỹ thuật điện tử - viễn thông');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7510303', 'Công nghệ kỹ thuật điều khiển và tự động hóa');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('75104', 'Công nghệ hoá học, vật liệu, luyện kim và môi trường');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7510401', 'Công nghệ kỹ thuật hoá học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7510402', 'Công nghệ vật liệu');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7510406', 'Công nghệ kỹ thuật môi trường');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7510407', 'Công nghệ kỹ thuật hạt nhân');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('75106', 'Quản lý công nghiệp');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7510601', 'Quản lý công nghiệp');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7510604', 'Kinh tế công nghiệp');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7510605', 'Logistics và Quản lý chuỗi cung ứng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('75107', 'Công nghệ dầu khí và khai thác');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7510701', 'Công nghệ dầu khí và khai thác dầu');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('75108', 'Công nghệ kỹ thuật in');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7510801', 'Công nghệ kỹ thuật in');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('75190', 'Khác');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('752', 'Kỹ thuật');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('75201', 'Kỹ thuật cơ khí và cơ kỹ thuật');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7520101', 'Cơ kỹ thuật');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7520103', 'Kỹ thuật cơ khí');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7520114', 'Kỹ thuật cơ điện tử');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7520115', 'Kỹ thuật nhiệt');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7520116', 'Kỹ thuật cơ khí động lực');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7520117', 'Kỹ thuật công nghiệp');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7520118', 'Kỹ thuật hệ thống công nghiệp');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7520120', 'Kỹ thuật hàng không');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7520121', 'Kỹ thuật không gian');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7520122', 'Kỹ thuật tàu thuỷ');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7520130', 'Kỹ thuật ô tô');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7520137', 'Kỹ thuật in');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('75202', 'Kỹ thuật điện, điện tử và viễn thông');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7520201', 'Kỹ thuật điện');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7520204', 'Kỹ thuật ra đa- dẫn đường');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7520205', 'Kỹ thuật thuỷ âm');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7520207', 'Kỹ thuật điện tử -  viễn thông');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7520212', 'Kỹ thuật y sinh');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7520216', 'Kỹ thuật điều khiển và tự động hoá');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('75203', 'Kỹ thuật hoá học, vật liệu, luyện kim và môi trường');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7520301', 'Kỹ thuật hoá học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7520309', 'Kỹ thuật vật liệu');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7520310', 'Kỹ thuật vật liệu kim loại');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7520312', 'Kỹ thuật dệt');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7520320', 'Kỹ thuật môi trường');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('75204', 'Vật lý kỹ thuật');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7520401', 'Vật lý kỹ thuật');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7520402', 'Kỹ thuật hạt nhân');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('75205', 'Kỹ thuật địa chất, địa vật lý và trắc địa');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7520501', 'Kỹ thuật địa chất');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7520502', 'Kỹ thuật địa vật lý');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7520503', 'Kỹ thuật trắc địa - bản đồ');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('75206', 'Kỹ thuật mỏ');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7520601', 'Kỹ thuật mỏ');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7520602', 'Kỹ thuật thăm dò và khảo sát');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7520604', 'Kỹ thuật dầu khí');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7520607', 'Kỹ thuật tuyển khoáng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('75290', 'Khác');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7529001', 'Kỹ thuật biển');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('754', 'Sản xuất và chế biến');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('75401', 'Chế biến lương thực, thực phẩm và đồ uống');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7540101', 'Công nghệ thực phẩm');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7540102', 'Kỹ thuật thực phẩm');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7540104', 'Công nghệ sau thu hoạch');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7540105', 'Công nghệ chế biến thuỷ sản');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7540106', 'Đảm bảo chất lượng và an toàn thực phẩm');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('75402', 'Sản xuất, chế biến sợi, vải, giày, da');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7540202', 'Công nghệ sợi, dệt');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7540203', 'Công nghệ vật liệu dệt, may');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7540204', 'Công nghệ dệt, may');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7540206', 'Công nghệ da giày');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('75490', 'Khác');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7549001', 'Công nghệ chế biến lâm sản');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('758', 'Kiến trúc và xây dựng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('75801', 'Kiến trúc và quy hoạch');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7580101', 'Kiến trúc');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7580102', 'Kiến trúc cảnh quan');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7580103', 'Kiến trúc nội thất');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7580104', 'Kiến trúc đô thị');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7580105', 'Quy hoạch vùng và đô thị');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7580106', 'Quản lý đô thị và công trình');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7580108', 'Thiết kế nội thất');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7580111', 'Bảo tồn di sản kiến trúc - đô thị');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7580112', 'Đô thị học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('75802', 'Xây dựng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7580201', 'Kỹ thuật xây dựng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7580202', 'Kỹ thuật xây dựng công trình thuỷ');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7580203', 'Kỹ thuật xây dựng công trình biển');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7580205', 'Kỹ thuật xây dựng công trình giao thông');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7580210', 'Kỹ thuật cơ sở hạ tầng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7580211', 'Địa kỹ thuật xây dựng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7580212', 'Kỹ thuật tài nguyên nước');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7580213', 'Kỹ thuật cấp thoát nước');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('75803', 'Quản lý xây dựng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7580301', 'Kinh tế xây dựng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7580302', 'Quản lý xây dựng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('75890', 'Khác');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('762', 'Nông, lâm nghiệp và thuỷ sản');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('76201', 'Nông nghiệp');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7620101', 'Nông nghiệp');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7620102', 'Khuyến nông');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7620103', 'Khoa học đất');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7620105', 'Chăn nuôi');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7620109', 'Nông học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7620110', 'Khoa học cây trồng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7620112', 'Bảo vệ thực vật');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7620113', 'Công nghệ rau hoa quả và cảnh quan');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7620114', 'Kinh doanh nông nghiệp');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7620115', 'Kinh tế nông nghiệp');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7620116', 'Phát triển nông thôn');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('76202', 'Lâm nghiệp');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7620201', 'Lâm học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7620202', 'Lâm nghiệp đô thị');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7620205', 'Lâm sinh');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7620211', 'Quản lý tài nguyên rừng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('76203', 'Thuỷ sản');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7620301', 'Nuôi trồng thuỷ sản');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7620302', 'Bệnh học thủy sản');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7620303', 'Khoa học thủy sản');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7620304', 'Khai thác thuỷ sản');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7620305', 'Quản lý thủy sản');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('76290', 'Khác');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('764', 'Thú y');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('76401', 'Thú y');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7640101', 'Thú y');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('76490', 'Khác');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('772', 'Sức khoẻ');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('77201', 'Y học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7720101', 'Y khoa');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7720110', 'Y học dự phòng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7720115', 'Y học cổ truyền');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('77202', 'Dược học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7720201', 'Dược học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7720203', 'Hoá dược');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('77203', 'Điều dưỡng - hộ sinh');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7720301', 'Điều dưỡng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7720302', 'Hộ sinh');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('77204', 'Dinh dưỡng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7720401', 'Dinh dưỡng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('77205', 'Răng - Hàm - Mặt (Nha khoa)');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7720501', 'Răng - Hàm - Mặt');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7720502', 'Kỹ thuật phục hình răng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('77206', 'Kỹ thuật Y học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7720601', 'Kỹ thuật xét nghiệm y học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7720602', 'Kỹ thuật hình ảnh y học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7720603', 'Kỹ thuật phục hồi chức năng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('77207', 'Y tế công cộng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7720701', 'Y tế công cộng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('77208', 'Quản lý Y tế');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7720801', 'Tổ chức và quản lý y tế');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7720802', 'Quản lý bệnh viện');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('77290', 'Khác');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7729001', 'Y sinh học thể dục thể thao');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('776', 'Dịch vụ xã hội');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('77601', 'Công tác xã hội');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7760101', 'Công tác xã hội');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7760102', 'Công tác thanh thiếu niên');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('8760103', 'Hỗ trợ giáo dục người khuyết tật');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('77690', 'Khác');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('781', 'Du lịch, khách sạn, thể thao và dịch vụ cá nhân');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('78101', 'Du lịch');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7810101', 'Du lịch');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7810103', 'Quản trị dịch vụ du lịch và lữ hành');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('78102', 'Khách sạn, nhà hàng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7810201', 'Quản trị khách sạn');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7810202', 'Quản trị nhà hàng và dịch vụ ăn uống');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('78103', 'Thể dục, thể thao');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7810301', 'Quản lý thể dục thể thao');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('78105', 'Kinh tế gia đình');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7810501', 'Kinh tế gia đình');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('78190', 'Khác');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('784', 'Dịch vụ vận tải');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('78401', 'Khai thác vận tải');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7840101', 'Khai thác vận tải');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7840102', 'Quản lý hoạt động bay');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7840104', 'Kinh tế vận tải');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7840106', 'Khoa học hàng hải');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('78490', 'Khác');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('785', 'Môi trường và bảo vệ môi trường');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('78501', 'Quản lý tài nguyên và môi trường');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7850101', 'Quản lý tài nguyên và môi trường');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7850102', 'Kinh tế tài nguyên thiên nhiên');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7850103', 'Quản lý đất đai');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('78502', 'Dịch vụ an toàn lao động và vệ sinh công nghiệp');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7850201', 'Bảo hộ lao động');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('78590', 'Khác');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('786', 'An ninh, Quốc phòng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('78601', 'An ninh và trật tự xã hội');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7860101', 'Trinh sát an ninh');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7860102', 'Trinh sát cảnh sát');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7860104', 'Điều tra hình sự');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7860108', 'Kỹ thuật hình sự');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7860109', 'Quản lý nhà nước về an ninh trật tự');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7860110', 'Quản lý trật tự an toàn giao thông');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7860111', 'Thi hành án hình sự và hỗ trợ tư pháp');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7860112', 'Tham mưu, chỉ huy công an nhân dân');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7860113', 'Phòng cháy chữa cháy và cứu nạn cứu hộ');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7860116', 'Hậu cần công an nhân dân');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7860117', 'Tình báo an ninh');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('78602', 'Quân sự');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7860201', 'Chỉ huy tham mưu Lục quân');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7860202', 'Chỉ huy tham mưu Hải quân');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7860203', 'Chỉ huy tham mưu Không quân');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7860204', 'Chỉ huy tham mưu Phòng không');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7860205', 'Chỉ huy tham mưu Pháo binh');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7860206', 'Chỉ huy tham mưu Tăng - thiết giáp');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7860207', 'Chỉ huy tham mưu Đặc công');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7860214', 'Biên phòng');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7860217', 'Tình báo quân sự');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7860218', 'Hậu cần quân sự');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7860220', 'Chỉ huy tham mưu thông tin');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7860222', 'Quân sự cơ sở');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7860226', 'Chỉ huy kỹ thuật Phòng không');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7860227', 'Chỉ huy kỹ thuật Tăng - thiết giáp');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7860228', 'Chỉ huy kỹ thuật Công binh');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7860229', 'Chỉ huy kỹ thuật Hoá học');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7860231', 'Trinh sát kỹ thuật');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7860232', 'Chỉ huy kỹ thuật Hải quân');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('7860233', 'Chỉ huy kỹ thuật tác chiến điện tử');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('78690', 'Khác');
INSERT INTO "Entrance_Scores"."majorEntities" (code, name) VALUES ('790', 'Khác');