INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('ANH', 'Học viện An Ninh Nhân Dân');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('ANS', 'Đại học An Ninh Nhân Dân');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('BKA', 'Đại học Bách Khoa Hà Nội');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('BPH', 'Học viện Biên Phòng - Phía Bắc');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('BPS', 'Học viện Biên Phòng - Phía Nam');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('BVH', 'Học viện Công Nghệ Bưu Chính Viễn Thông');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('BVS', 'Học viện Công Nghệ Bưu Chính Viễn Thông (phía Nam)');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('CSH', 'Học viện Cảnh Sát Nhân Dân');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('CSS', 'Đại học Cảnh Sát Nhân Dân');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('CTQ', 'Đại học Tài Chính Kế Toán');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DAD', 'Đại học Đông Á');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DBD', 'Đại học Bình Dương');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DBG', 'Ðh Nông Lâm Bắc Giang');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DBH', 'Đại học Quốc Tế Bắc Hà');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DBL', 'Đại học Bạc Liêu');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DBV', 'Đại học Bà Rịa - Vũng Tàu');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DCA', 'Đại học Chu Văn An');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DCD', 'Đại học Công Nghệ Đồng Nai');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DCDC', 'Đại học Công Nghệ Đồng Nai- Hệ Cđ');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DCG', 'Đại học Công Nghệ Thông Tin Gia Định');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DCH', 'Trường Sĩ Quan Đặc Công - Kv Phía Bắc');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DCL', 'Đại học Cửu Long');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DCN', 'Đại học Công Nghiệp Hà Nội');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DCQ', 'Đại học Tư Thục Công Nghệ Và Quản Lý Hữu Nghị');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DCS', 'Trường Sĩ Quan Đặc Công - Kv Phía Nam');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DCT', 'Đại học Công Nghiệp Thực Phẩm Tp.hcm');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DDD', 'Đại học Dân Lập Đông Đô');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DDF', 'Đại học Ngoại Ngữ - Đh Đà Nẵng');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DDK', 'Đại học Bách Khoa - Đh Đà Nẵng');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DDL', 'Đại học Điện Lực');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DDM', 'Đại học Công Nghiệp Quảng Ninh');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DDN', 'Đại học Đại Nam');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DDP', 'Phân Hiệu Đh Đà Nẵng Tại Kontum');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DDQ', 'Đại học Kinh Tế - Đh Đà Nẵng');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DDS', 'Đại học Sư Phạm - Đh Đà Nẵng');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DDT', 'Đại học Dân Lập Duy Tân');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DDY', 'Khoa Y Dược - Đh Đà Nẵng');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DHA', 'Khoa Luật Đh Huế');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DHB', 'Đại học Dân Lập Hồng Bàng');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DHC', 'Khoa Giáo Dục Thể Chất - Đh Huế');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DHD', 'Khoa Du Lịch - Đh Huế');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DHF', 'Đại học Ngoại Ngữ - Đh Huế');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DHH', 'Đại học Hà Hoa Tiên');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DHK', 'Đại học Kinh Tế - Đh Huế');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DHL', 'Đại học Nông Lâm - Đh Huế');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DHN', 'Đại học Nghệ Thuật - Đh Huế');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DHP', 'Đại học Dân Lập Hải Phòng');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DHQ', 'Phân Hiệu Đh Huế Tại Quảng Trị');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DHS', 'Đại học Sư Phạm - Đh Huế');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DHT', 'Đại học Khoa Học - Đh Huế');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DHV', 'Đại học Hùng Vương Tphcm');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DHY', 'Đại học Y Dược - Đh Huế');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DKB', 'Đại học Kinh Tế Kỹ Thuật Bình Dương');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DKC', 'Đại học Kỹ Thuật - Công Nghệ Tphcm');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DKH', 'Đại học Dược Hà Nội');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DKK', 'Đại học Kinh Tế Kỹ Thuật Công Nghiệp');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DKT', 'Đại học Kinh Tế- Kỹ Thuật Hải Dương');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DKT1', 'Đại học Kinh Tế- Kỹ Thuật Hải Dương- Hệ Cđ');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DKY', 'Đại học Kỹ Thuật Y Tế Hải Dương');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DLA', 'Đại học Kinh Tế Công Nghiệp Long An');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DLH', 'Đại học Lạc Hồng');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DLS', 'Đại học Lao Động - Xã Hội (phía Nam)');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DLX', 'Đại học Lao Động - Xã Hội');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DMS', 'Đại học Tài Chính Marketing');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DMT', 'Đại học Tài Nguyên Và Môi Trường Hà Nội');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DNB', 'Đại học Hoa Lư Ninh Bình');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DNH', 'Học viện Khoa Học Quân Sự (phía Bắc)');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DNS', 'Học viện Khoa Học Quân Sự- Hệ Dân Sự (thi Ở Phía Nam)');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DNT', 'Đại học Ngoại Ngữ - Tin Học Tphcm');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DNU', 'Đại học Đồng Nai');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DNV', 'Đại học Nội Vụ Hà Nội');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DPC', 'Đại học Phan Châu Trinh');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DPD', 'Đại học Dân Lập Phương Đông');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DPQ', 'Đại học Phạm Văn Đồng');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DPX', 'Đại học Phú Xuân');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DPY', 'Đại học Phú Yên');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DQB', 'Đại học Quảng Bình');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DQH', 'Học viện Kĩ Thuật Quân Sự - Hệ Dân Sự - Phía Bắc');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DQK', 'Đại học Kinh Doanh Và Công Nghệ Hà Nội');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DQN', 'Đại học Quy Nhơn');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DQS', 'Học viện Kĩ Thuật Quân Sự - Hệ Dân Sự - Thi Phía Nam');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DQT', 'Đại học Quang Trung');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DQU', 'Đại học Quảng Nam');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DSD', 'Đại học Sân Khấu Điện Ảnh Tp Hcm');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DSG', 'Đại học Công Nghệ Sài Gòn');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DTA', 'Đại học Thành Tây');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DTB', 'Đại học Thái Bình');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DTC', 'Đại học Công Nghệ Thông Tin Và Truyền Thông');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DTD', 'Đại học Tây Đô');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DTE', 'Đại học Kinh Tế quản Trị Kinh Doanh Đh Thái Nguyên');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DTF', 'Khoa Ngoại Ngữ - Đh Thái Nguyên');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DTH', 'Đại học Hoa Sen');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DTK', 'Đại học Kỹ Thuật Công Nghiệp - Đh Thái Nguyên');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DTL', 'Đại học Thăng Long');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DTM', 'Đại học Tài Nguyên Môi Trường Tphcm');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DTN', 'Đại học Nông Lâm - Đh Thái Nguyên');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DTQ', 'Khoa Quốc Tế - Đh Thái Nguyên');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DTS', 'Đại học Sư Phạm Đh Thái Nguyên');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DTT', 'Đại học Tôn Đức Thắng');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DTV', 'Đại học Dân Lập Lương Thế Vinh');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DTY', 'Đại học Y Dược - Đh Thái Nguyên');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DTZ', 'Đại học Khoa Học - Đh Thái Nguyên');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DVH', 'Đại học Văn Hiến');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DVL', 'Đại học Dân Lập Văn Lang');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DVP', 'Đại học Trưng Vương');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DVT', 'Đại học Trà Vinh');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DVX', 'Đại học Công Nghệ Vạn Xuân');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DYD', 'Đại học Yersin Đà Lạt');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DYH', 'Học viện Quân Y (dân Sự Phía Bắc)');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('DYS', 'Học viện Quân Y - Phía Nam (dân Sự)');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('EIU', 'Đại học Quốc Tế Miền Đông');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('FBU', 'Đại học Tài Chính - Ngân Hàng Hà Nội');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('FPT', 'Đại học Fpt');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('GHA', 'Đại học Giao Thông Vận Tải');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('GNT', 'Đại học Sư Phạm Nghệ Thuật Trung Ương');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('GSA', 'Đại học Giao Thông Vận Tải (phía Nam)');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('GTA', 'Đại học Công Nghệ Giao Thông Vận Tải');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('GTS', 'Đại học Giao Thông Vận Tải Tphcm');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('HAH', 'Học viện Chính Trị - Phía Bắc');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('HAS', 'Học viện Chính Trị - Phía Nam');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('HBU', 'Đại học Hòa Bình');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('HCH', 'Học viện Hành Chính Quốc Gia (phía Bắc)');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('HCP', 'Học viện Chính Sách Và Phát Triển');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('HCS', 'Học viện Hành Chính Quốc Gia (phía Nam)');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('HDT', 'Đại học Hồng Đức');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('HEH', 'Học viện Hậu Cần - Phía Bắc');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('HES', 'Học viện Hậu Cần - Thi Phía Nam');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('HFH', 'Học viện Hậu Cần - Hệ Dân Sự (phía Bắc)');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('HFS', 'Học viện Hậu Cần - Hệ Dân Sự (thi Phía Nam)');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('HGH', 'Trường Sĩ Quan Phòng Hoá - Kv Phía Bắc');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('HGS', 'Trường Sĩ Quan Phòng Hoá -thi Kv Phía Nam');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('HHA', 'Đại học Hàng Hải');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('HHK', 'Học viện Hàng Không Việt Nam');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('HHT', 'Đại học Hà Tĩnh');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('HQH', 'Học viện Hải Quân - Phía Bắc');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('HQS', 'Học viện Hải Quân - Phía Nam');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('HQT', 'Học viện Ngoại Giao');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('HTC', 'Học viện Tài Chính');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('HUI', 'Đại học Công Nghiệp Tphcm');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('HVA', 'Học viện Âm Nhạc Huế');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('HVQ', 'Học viện Quản Lí Giáo Dục');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('HYD', 'Học viện Y Dược Học Cổ Truyền Việt Nam');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('KCN', 'Đại học Khoa Học Và Công Nghệ Hà Nội');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('KGH', 'Trường Sĩ Quan Không Quân -thi Phía Bắc');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('KGS', 'Trường Sĩ Quan Không Quân -thi Phía Nam');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('KHA', 'Đại học Kinh Tế Quốc Dân');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('KMA', 'Học viện Kỹ Thuật Mật Mã');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('KPH', 'Học viện Phòng Không - Không Quân - Kĩ Sư Hàng Không - Thi Ở Phía Bắc');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('KPS', 'Học viện Phòng Không - Không Quân - Kĩ Sư Hàng Không - Thi Ở Phía Nam');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('KQH', 'Học viện Kĩ Thuật Quân Sự Hệ Quân Sự Phía Bắc');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('KQS', 'Học viện Kĩ Thuật Quân Sự - Hệ Quân Sự - Thi Phía Nam');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('KSA', 'Đại học Kinh Tế Tphcm');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('KTA', 'Đại học Kiến Trúc Hà Nội');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('KTC', 'Đại học Kinh Tế -tài Chính Tphcm');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('KTD', 'Đại học Kiến Trúc Đà Nẵng');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('KTS', 'Đại học Kiến Trúc Tphcm');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('LAH', 'Trường Sĩ Quan Lục Quân 1 - Phía Bắc');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('LAS', 'Học viện Sĩ Quan Lục Quân I - Thi Ở Phía Nam');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('LBH', 'Trường Sĩ Quan Lục Quân 2 - Phía Bắc');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('LBS', 'Trường Sĩ Quan Lục Quân 2 - Phía Nam');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('LCH', 'Đại học Chính Trị - Thi Ở Phía Bắc');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('LCS', 'Đại học Chính Trị - Thi Ở Phía Nam');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('LDA', 'Đại học Công Đoàn');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('LNH', 'Đại học Lâm Nghiệp - Phía Bắc');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('LNS', 'Đại học Lâm Nghiệp - Phía Nam');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('LPH', 'Đại học Luật Hà Nội');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('LPS', 'Đại học Luật Tphcm');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('MBS', 'Đại học Mở Tphcm');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('MDA', 'Đại học Mỏ Địa Chất');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('MHN', 'Đại học Mở Hà Nội');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('MTC', 'Đại học Mỹ Thuật Công Nghiệp');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('MTH', 'Đại học Mỹ Thuật Việt Nam');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('MTS', 'Đại học Mỹ Thuật Tphcm');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('MTU', 'Đại học Xây Dựng Miền Tây');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('MTU1', 'Đại học Xây Dựng Miền Tây- Hệ Cđ');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('NHF', 'Đại học Hà Nội');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('NHH', 'Học viện Ngân Hàng');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('NHP', 'Học viện Ngân Hàng (phân Viện Phú Yên)');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('NHS', 'Đại học Ngân Hàng Tphcm');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('NLS', 'Đại học Nông Lâm Tphcm');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('NNH', 'Đại học Nông Nghiệp Hà Nội');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('NQH', 'Học viện Khoa Học Quân Sự - Phía Bắc');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('NQS', 'Học viện Khoa Học Quân Sự - Phía Nam');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('NTH', 'Đại học Ngoại Thương');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('NTS', 'Đại học Ngoại Thương (phía Nam)');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('NTT', 'Đại học Nguyễn Tất Thành');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('NTU', 'Đại học Nguyễn Trãi');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('NVH', 'Học viện Âm Nhạc Quốc Gia Việt Nam');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('NVS', 'Nhạc Viện Tphcm');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('PBH', 'Trường Sĩ Quan Pháo Binh - Phía Bắc');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('PBS', 'Trường Sĩ Quan Pháo Binh - Thi Phía Nam');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('PCH', 'Đại học Phòng Cháy Chữa Cháy Phía Bắc');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('PCS', 'Đại học Phòng Cháy Chữa Cháy (phía Nam)');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('PKH', 'Học viện Phòng Không - Không Quân -chỉ Huy Tham Mưu - Thi Ở Phía Bắc');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('PKS', 'Học viện Phòng Không - Không Quân - Chỉ Huy Tham Mưu - Thi Ở Phía Nam');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('PVU', 'Đại học Dầu Khí Việt Nam');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('QHE', 'Đại học Kinh Tế - Đh Quốc Gia Hà Nội');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('QHF', 'Đại học Ngoại Ngữ - Đh Quốc Gia Hà Nội');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('QHI', 'Đại học Công Nghệ - Đh Quốc Gia Hà Nội');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('QHL', 'Khoa Luật - Đh Quốc Gia Hà Nội');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('QHQ', 'Khoa Quốc Tế - Đh Quốc Gia Hà Nội');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('QHS', 'Khoa Sư Phạm - Đh Quốc Gia Hà Nội');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('QHT', 'Đại học Khoa Học Tự Nhiên - Đh Quốc Gia Hà Nội');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('QHX', 'Đại học Khoa Học Xã Hội Và Nhân Văn - Đh Quốc Gia Hà Nội');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('QHY', 'Khoa Y Dược - Đh Quốc Gia Hà Nội');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('QSB', 'Đại học Bách Khoa - Đh Quốc Gia Tphcm');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('QSC', 'Đại học Công Nghệ Thông Tin - Đh Quốc Gia Tphcm');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('QSK', 'Khoa Kinh Tế - Luật - Đh Quốc Gia Tphcm');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('QSQ', 'Đại học Quốc Tế - Đh Quốc Gia Tphcm');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('QST', 'Đại học Khoa Học Tự Nhiên - Đh Quốc Gia Tphcm');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('QSX', 'Đại học Khoa Học Xã Hội Và Nhân Văn - Đh Quốc Gia Tphcm');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('QSY', 'Khoa Y (đhqg Hcm)');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('RHM', 'Đại học Răng - Hàm - Mặt');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('RMI', 'Đại học Quốc Tế Rmit Việt Nam');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('SDU', 'Đại học Sao Đỏ');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('SGD', 'Đại học Sài Gòn');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('SKD', 'Đại học Sân Khấu Điện Ảnh');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('SKH', 'Đại học Sư Phạm Kỹ Thuật Hưng Yên');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('SKN', 'Đại học Sư Phạm Kỹ Thuật Nam Định');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('SKV', 'Đại học Sư Phạm Kỹ Thuật Vinh');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('SNH', 'Trường Sĩ Quan Công Binh - Thi Phía Bắc');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('SNS', 'Trường Sĩ Quan Công Binh - Phía Nam');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('SP2', 'Đại học Sư Phạm Hà Nội 2');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('SPD', 'Đại học Đồng Tháp');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('SPH', 'Đại học Sư Phạm Hà Nội');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('SPK', 'Đại học Sư Phạm Kỹ Thuật Tphcm');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('SPS', 'Đại học Sư Phạm Tphcm');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('STS', 'Đại học Sư Phạm Thể Dục Thể Thao Tphcm');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('TAG', 'Đại học An Giang');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('TBD', 'Đại học Thái Bình Dương');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('TCT', 'Đại học Cần Thơ');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('TDB', 'Đại học Thể Dục Thể Thao Bắc Ninh');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('TDD', 'Đại học Thành Đô');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('TDH', 'Đại học Sư Phạm Thể Dục Thể Thao Hà Nội');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('TDL', 'Đại học Đà Lạt');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('TDM', 'Đại học Thủ Dầu Một');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('TDS', 'Đại học Thể Dục Thể Thao Tphcm');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('TDV', 'Đại học Vinh');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('TGC', 'Học viện Báo Chí - Tuyên Truyền');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('TGH', 'Trường Sĩ quan Tăng Thiết Giáp - Thi Phía Bắc');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('TGS', 'Trường Sĩ quan Tăng Thiết Giáp- Thi Phía Nam');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('THP', 'Đại học Hải Phòng');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('THV', 'Đại học Hùng Vương');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('TLA', 'Đại học Thuỷ Lợi');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('TLS', 'Đại học Thuỷ Lợi (phía Nam)');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('TMA', 'Đại học Thương Mại');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('TSB', 'Đại học Nha Trang - Dự Thi Tại Bắc Ninh');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('TSN', 'Đại học Nha Trang');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('TSS', 'Đại học Nha Trang - Dự Thi Tại Cần Thơ');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('TTB', 'Đại học Tây Bắc');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('TTD', 'Đại học Thể Dục Thể Thao Đà Nẵng');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('TTG', 'Đại học Tiền Giang');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('TTH', 'Trường Sĩ Quan Thông Tin - Phía Bắc');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('TTN', 'Đại học Tây Nguyên');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('TTQ', 'Đại học Quốc Tế Sài Gòn');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('TTS', 'Trường Sĩ Quan Thông Tin - Phía Nam');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('TTU', 'Đại học Tân Tạo');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('TYS', 'Đại học Y Khoa Phạm Ngọc Thạch');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('VGU', 'Đại học Việt Đức');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('VHD', 'Đại học Công Nghiệp Việt - Hung');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('VHH', 'Đại học Văn Hoá Hà Nội');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('VHS', 'Đại học Văn Hoá Tphcm');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('VPH', 'Trường Sĩ Quan Kỹ Thuật Quân Sự- Vin-hem-pich- Hệ Quân Sự- Phía Bắc');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('VPS', 'Trường Sĩ Quan Kỹ Thuật Quân Sự- Vin-hem-pich- Hệ Quân Sự- Phía Nam');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('VTT', 'Đại học Võ Trường Toản');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('VUI', 'Đại học Công Nghiệp Việt Trì');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('XDA', 'Đại học Xây Dựng Hà Nội');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('XDT', 'Đại học Xây Dựng Miền Trung');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('YCT', 'Đại học Y Dược Cần Thơ');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('YDD', 'Đại học Điều Dưỡng Nam Định');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('YDS', 'Đại học Y Dược Tphcm');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('YHB', 'Đại học Y Hà Nội');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('YKV', 'Đại học Y Khoa Vinh');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('YPB', 'Đại học Y Hải Phòng');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('YQH', 'Học viện Quân Y - Phía Bắc');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('YQS', 'Học viện Quân Y - Phía Nam');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('YTB', 'Đại học Y Thái Bình');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('YTC', 'Đại học Y Tế Công Cộng');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('ZCH', 'Trường Sĩ Quan Công Binh Hệ Dân Sự');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('ZNH', 'Đại học Văn Hoá - Nghệ Thuật Quân Đội - Phía Bắc');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('ZNS', 'Đại học Văn Hoá - Nghệ Thuật Quân Đội - Phía Nam');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('ZPH', 'Đại học Trần Đại Nghĩa');
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name) VALUES ('ZTH', 'Trường Sĩ Quan Thông Tin');