INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('ANH', 'Học viện An Ninh Nhân Dân', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('ANS', 'Đại học An Ninh Nhân Dân', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('BKA', 'Đại học Bách Khoa Hà Nội', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('BPH', 'Học viện Biên Phòng - Phía Bắc', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('BPS', 'Học viện Biên Phòng - Phía Nam', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('BVH', 'Học viện Công Nghệ Bưu Chính Viễn Thông', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('BVS', 'Học viện Công Nghệ Bưu Chính Viễn Thông (phía Nam)', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('CSH', 'Học viện Cảnh Sát Nhân Dân', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('CSS', 'Đại học Cảnh Sát Nhân Dân', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('CTQ', 'Đại học Tài Chính Kế Toán', 42);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DAD', 'Đại học Đông Á', 57);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DBD', 'Đại học Bình Dương', 3);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DBG', 'Ðh Nông Lâm Bắc Giang', 7);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DBH', 'Đại học Quốc Tế Bắc Hà', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DBL', 'Đại học Bạc Liêu', 61);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DBV', 'Đại học Bà Rịa - Vũng Tàu', 2);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DCA', 'Đại học Chu Văn An', 21);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DCD', 'Đại học Công Nghệ Đồng Nai', 59);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DCDC', 'Đại học Công Nghệ Đồng Nai- Hệ Cđ', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DCG', 'Đại học Công Nghệ Thông Tin Gia Định', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DCH', 'Trường Sĩ Quan Đặc Công - Kv Phía Bắc', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DCL', 'Đại học Cửu Long', 54);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DCN', 'Đại học Công Nghiệp Hà Nội', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DCQ', 'Đại học Tư Thục Công Nghệ Và Quản Lý Hữu Nghị', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DCS', 'Trường Sĩ Quan Đặc Công - Kv Phía Nam', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DCT', 'Đại học Công Nghiệp Thực Phẩm Tp.hcm', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DDD', 'Đại học Dân Lập Đông Đô', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DDF', 'Đại học Ngoại Ngữ - đại học Đà Nẵng', 57);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DDK', 'Đại học Bách Khoa - đại học Đà Nẵng', 57);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DDL', 'Đại học Điện Lực', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DDM', 'Đại học Công Nghiệp Quảng Ninh', 43);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DDN', 'Đại học Đại Nam', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DDP', 'Phân Hiệu đại học Đà Nẵng Tại Kontum', 28);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DDQ', 'Đại học Kinh Tế - đại học Đà Nẵng', 57);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DDS', 'Đại học Sư Phạm - đại học Đà Nẵng', 57);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DDT', 'Đại học Dân Lập Duy Tân', 57);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DDY', 'Khoa Y Dược - đại học Đà Nẵng', 57);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DHA', 'Khoa Luật đại học Huế', 49);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DHB', 'Đại học Dân Lập Hồng Bàng', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DHC', 'Khoa Giáo Dục Thể Chất - đại học Huế', 49);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DHD', 'Khoa Du Lịch - đại học Huế', 49);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DHF', 'Đại học Ngoại Ngữ - đại học Huế', 49);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DHH', 'Đại học Hà Hoa Tiên', 16);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DHK', 'Đại học Kinh Tế - đại học Huế', 49);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DHL', 'Đại học Nông Lâm - đại học Huế', 49);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DHN', 'Đại học Nghệ Thuật - đại học Huế', 49);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DHP', 'Đại học Dân Lập Hải Phòng', 23);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DHQ', 'Phân Hiệu đại học Huế Tại Quảng Trị', 44);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DHS', 'Đại học Sư Phạm - đại học Huế', 49);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DHT', 'Đại học Khoa Học - đại học Huế', 49);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DHV', 'Đại học Hùng Vương Tphcm', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DHY', 'Đại học Y Dược - đại học Huế', 49);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DKB', 'Đại học Kinh Tế Kỹ Thuật Bình Dương', 3);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DKC', 'Đại học Kỹ Thuật - Công Nghệ Tphcm', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DKH', 'Đại học Dược Hà Nội', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DKK', 'Đại học Kinh Tế Kỹ Thuật Công Nghiệp', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DKT', 'Đại học Kinh Tế- Kỹ Thuật Hải Dương', 22);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DKT1', 'Đại học Kinh Tế- Kỹ Thuật Hải Dương- Hệ Cđ', 22);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DKY', 'Đại học Kỹ Thuật Y Tế Hải Dương', 22);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DLA', 'Đại học Kinh Tế Công Nghiệp Long An', 30);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DLH', 'Đại học Lạc Hồng', 59);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DLS', 'Đại học Lao Động - Xã Hội (phía Nam)', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DLX', 'Đại học Lao Động - Xã Hội', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DMS', 'Đại học Tài Chính Marketing', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DMT', 'Đại học Tài Nguyên Và Môi Trường Hà Nội', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DNB', 'Đại học Hoa Lư Ninh Bình', 36);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DNH', 'Học viện Khoa Học Quân Sự (phía Bắc)', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DNS', 'Học viện Khoa Học Quân Sự- Hệ Dân Sự (thi Ở Phía Nam)', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DNT', 'Đại học Ngoại Ngữ - Tin Học Tphcm', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DNU', 'Đại học Đồng Nai', 59);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DNV', 'Đại học Nội Vụ Hà Nội', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DPC', 'Đại học Phan Châu Trinh', 41);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DPD', 'Đại học Dân Lập Phương Đông', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DPQ', 'Đại học Phạm Văn Đồng', 42);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DPX', 'Đại học Phú Xuân', 49);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DPY', 'Đại học Phú Yên', 39);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DQB', 'Đại học Quảng Bình', 40);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DQH', 'Học viện Kĩ Thuật Quân Sự - Hệ Dân Sự - Phía Bắc', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DQK', 'Đại học Kinh Doanh Và Công Nghệ Hà Nội', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DQN', 'Đại học Quy Nhơn', 9);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DQS', 'Học viện Kĩ Thuật Quân Sự - Hệ Dân Sự - Thi Phía Nam', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DQT', 'Đại học Quang Trung', 9);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DQU', 'Đại học Quảng Nam', 41);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DSD', 'Đại học Sân Khấu Điện Ảnh Tp Hcm', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DSG', 'Đại học Công Nghệ Sài Gòn', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DTA', 'Đại học Thành Tây', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DTB', 'Đại học Thái Bình', 47);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DTC', 'Đại học Công Nghệ Thông Tin Và Truyền Thông', 48);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DTD', 'Đại học Tây Đô', 13);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DTE', 'Đại học Kinh Tế quản Trị Kinh Doanh đại học Thái Nguyên', 48);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DTF', 'Khoa Ngoại Ngữ - đại học Thái Nguyên', 48);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DTH', 'Đại học Hoa Sen', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DTK', 'Đại học Kỹ Thuật Công Nghiệp - đại học Thái Nguyên', 48);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DTL', 'Đại học Thăng Long', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DTM', 'Đại học Tài Nguyên Môi Trường Tphcm', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DTN', 'Đại học Nông Lâm - đại học Thái Nguyên', 48);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DTQ', 'Khoa Quốc Tế - đại học Thái Nguyên', 48);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DTS', 'Đại học Sư Phạm đại học Thái Nguyên', 48);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DTT', 'Đại học Tôn Đức Thắng', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DTV', 'Đại học Dân Lập Lương Thế Vinh', 34);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DTY', 'Đại học Y Dược - đại học Thái Nguyên', 48);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DTZ', 'Đại học Khoa Học - đại học Thái Nguyên', 48);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DVH', 'Đại học Văn Hiến', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DVL', 'Đại học Dân Lập Văn Lang', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DVP', 'Đại học Trưng Vương', 55);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DVT', 'Đại học Trà Vinh', 51);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DVX', 'Đại học Công Nghệ Vạn Xuân', 35);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DYD', 'Đại học Yersin Đà Lạt', 32);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DYH', 'Học viện Quân Y (dân Sự Phía Bắc)', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('DYS', 'Học viện Quân Y - Phía Nam (dân Sự)', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('EIU', 'Đại học Quốc Tế Miền Đông', 3);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('FBU', 'Đại học Tài Chính - Ngân Hàng Hà Nội', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('FPT', 'Đại học Fpt', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('GHA', 'Đại học Giao Thông Vận Tải', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('GNT', 'Đại học Sư Phạm Nghệ Thuật Trung Ương', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('GSA', 'Đại học Giao Thông Vận Tải (phía Nam)', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('GTA', 'Đại học Công Nghệ Giao Thông Vận Tải', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('GTS', 'Đại học Giao Thông Vận Tải Tphcm', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('HAH', 'Học viện Chính Trị - Phía Bắc', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('HAS', 'Học viện Chính Trị - Phía Nam', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('HBU', 'Đại học Hòa Bình', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('HCH', 'Học viện Hành Chính Quốc Gia (phía Bắc)', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('HCP', 'Học viện Chính Sách Và Phát Triển', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('HCS', 'Học viện Hành Chính Quốc Gia (phía Nam)', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('HDT', 'Đại học Hồng Đức', 46);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('HEH', 'Học viện Hậu Cần - Phía Bắc', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('HES', 'Học viện Hậu Cần - Thi Phía Nam', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('HFH', 'Học viện Hậu Cần - Hệ Dân Sự (phía Bắc)', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('HFS', 'Học viện Hậu Cần - Hệ Dân Sự (thi Phía Nam)', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('HGH', 'Trường Sĩ Quan Phòng Hoá - Kv Phía Bắc', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('HGS', 'Trường Sĩ Quan Phòng Hoá -thi Kv Phía Nam', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('HHA', 'Đại học Hàng Hải', 23);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('HHK', 'Học viện Hàng Không Việt Nam', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('HHT', 'Đại học Hà Tĩnh', 19);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('HQH', 'Học viện Hải Quân - Phía Bắc', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('HQS', 'Học viện Hải Quân - Phía Nam', 25);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('HQT', 'Học viện Ngoại Giao', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('HTC', 'Học viện Tài Chính', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('HUI', 'Đại học Công Nghiệp Tphcm', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('HVA', 'Học viện Âm Nhạc Huế', 49);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('HVQ', 'Học viện Quản Lí Giáo Dục', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('HYD', 'Học viện Y Dược Học Cổ Truyền Việt Nam', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('KCN', 'Đại học Khoa Học Và Công Nghệ Hà Nội', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('KGH', 'Trường Sĩ Quan Không Quân -thi Phía Bắc', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('KGS', 'Trường Sĩ Quan Không Quân -thi Phía Nam', 25);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('KHA', 'Đại học Kinh Tế Quốc Dân', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('KMA', 'Học viện Kỹ Thuật Mật Mã', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('KPH', 'Học viện Phòng Không - Không Quân - Kĩ Sư Hàng Không - Thi Ở Phía Bắc', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('KPS', 'Học viện Phòng Không - Không Quân - Kĩ Sư Hàng Không - Thi Ở Phía Nam', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('KQH', 'Học viện Kĩ Thuật Quân Sự Hệ Quân Sự Phía Bắc', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('KQS', 'Học viện Kĩ Thuật Quân Sự - Hệ Quân Sự - Thi Phía Nam', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('KSA', 'Đại học Kinh Tế Tphcm', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('KTA', 'Đại học Kiến Trúc Hà Nội', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('KTC', 'Đại học Kinh Tế -tài Chính Tphcm', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('KTD', 'Đại học Kiến Trúc Đà Nẵng', 57);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('KTS', 'Đại học Kiến Trúc Tphcm', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('LAH', 'Trường Sĩ Quan Lục Quân 1 - Phía Bắc', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('LAS', 'Học viện Sĩ Quan Lục Quân I - Thi Ở Phía Nam', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('LBH', 'Trường Sĩ Quan Lục Quân 2 - Phía Bắc', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('LBS', 'Trường Sĩ Quan Lục Quân 2 - Phía Nam', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('LCH', 'Đại học Chính Trị - Thi Ở Phía Bắc', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('LCS', 'Đại học Chính Trị - Thi Ở Phía Nam', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('LDA', 'Đại học Công Đoàn', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('LNH', 'Đại học Lâm Nghiệp - Phía Bắc', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('LNS', 'Đại học Lâm Nghiệp - Phía Nam', 59);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('LPH', 'Đại học Luật Hà Nội', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('LPS', 'Đại học Luật Tphcm', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('MBS', 'Đại học Mở Tphcm', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('MDA', 'Đại học Mỏ Địa Chất', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('MHN', 'Đại học Mở Hà Nội', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('MTC', 'Đại học Mỹ Thuật Công Nghiệp', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('MTH', 'Đại học Mỹ Thuật Việt Nam', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('MTS', 'Đại học Mỹ Thuật Tphcm', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('MTU', 'Đại học Xây Dựng Miền Tây', 54);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('MTU1', 'Đại học Xây Dựng Miền Tây- Hệ Cđ', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('NHF', 'Đại học Hà Nội', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('NHH', 'Học viện Ngân Hàng', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('NHP', 'Học viện Ngân Hàng (phân Viện Phú Yên)', 39);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('NHS', 'Đại học Ngân Hàng Tphcm', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('NLS', 'Đại học Nông Lâm Tphcm', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('NNH', 'Đại học Nông Nghiệp Hà Nội', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('NQH', 'Học viện Khoa Học Quân Sự - Phía Bắc', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('NQS', 'Học viện Khoa Học Quân Sự - Phía Nam', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('NTH', 'Đại học Ngoại Thương', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('NTS', 'Đại học Ngoại Thương (phía Nam)', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('NTT', 'Đại học Nguyễn Tất Thành', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('NTU', 'Đại học Nguyễn Trãi', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('NVH', 'Học viện Âm Nhạc Quốc Gia Việt Nam', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('NVS', 'Nhạc Viện Tphcm', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('PBH', 'Trường Sĩ Quan Pháo Binh - Phía Bắc', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('PBS', 'Trường Sĩ Quan Pháo Binh - Thi Phía Nam', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('PCH', 'Đại học Phòng Cháy Chữa Cháy Phía Bắc', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('PCS', 'Đại học Phòng Cháy Chữa Cháy (phía Nam)', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('PKH', 'Học viện Phòng Không - Không Quân -chỉ Huy Tham Mưu - Thi Ở Phía Bắc', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('PKS', 'Học viện Phòng Không - Không Quân - Chỉ Huy Tham Mưu - Thi Ở Phía Nam', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('PVU', 'Đại học Dầu Khí Việt Nam', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('QHE', 'Đại học Kinh Tế - đại học Quốc Gia Hà Nội', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('QHF', 'Đại học Ngoại Ngữ - đại học Quốc Gia Hà Nội', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('QHI', 'Đại học Công Nghệ - đại học Quốc Gia Hà Nội', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('QHL', 'Khoa Luật - đại học Quốc Gia Hà Nội', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('QHQ', 'Khoa Quốc Tế - đại học Quốc Gia Hà Nội', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('QHS', 'Khoa Sư Phạm - đại học Quốc Gia Hà Nội', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('QHT', 'Đại học Khoa Học Tự Nhiên - đại học Quốc Gia Hà Nội', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('QHX', 'Đại học Khoa Học Xã Hội Và Nhân Văn - đại học Quốc Gia Hà Nội', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('QHY', 'Khoa Y Dược - đại học Quốc Gia Hà Nội', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('QSB', 'Đại học Bách Khoa - đại học Quốc Gia Tphcm', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('QSC', 'Đại học Công Nghệ Thông Tin - đại học Quốc Gia Tphcm', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('QSK', 'Khoa Kinh Tế - Luật - đại học Quốc Gia Tphcm', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('QSQ', 'Đại học Quốc Tế - đại học Quốc Gia Tphcm', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('QST', 'Đại học Khoa Học Tự Nhiên - đại học Quốc Gia Tphcm', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('QSX', 'Đại học Khoa Học Xã Hội Và Nhân Văn - đại học Quốc Gia Tphcm', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('QSY', 'Khoa Y (đại học quốc gia Tphcm)', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('RHM', 'Đại học Răng - Hàm - Mặt', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('RMI', 'Đại học Quốc Tế Rmit Việt Nam', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('SDU', 'Đại học Sao Đỏ', 22);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('SGD', 'Đại học Sài Gòn', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('SKD', 'Đại học Sân Khấu Điện Ảnh', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('SKH', 'Đại học Sư Phạm Kỹ Thuật Hưng Yên', 21);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('SKN', 'Đại học Sư Phạm Kỹ Thuật Nam Định', 34);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('SKV', 'Đại học Sư Phạm Kỹ Thuật Vinh', 35);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('SNH', 'Trường Sĩ Quan Công Binh - Thi Phía Bắc', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('SNS', 'Trường Sĩ Quan Công Binh - Phía Nam', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('SP2', 'Đại học Sư Phạm Hà Nội 2', 55);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('SPD', 'Đại học Đồng Tháp', 60);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('SPH', 'Đại học Sư Phạm Hà Nội', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('SPK', 'Đại học Sư Phạm Kỹ Thuật Tphcm', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('SPS', 'Đại học Sư Phạm Tphcm', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('STS', 'Đại học Sư Phạm Thể Dục Thể Thao Tphcm', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('TAG', 'Đại học An Giang', 1);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('TBD', 'Đại học Thái Bình Dương', 25);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('TCT', 'Đại học Cần Thơ', 13);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('TDB', 'Đại học Thể Dục Thể Thao Bắc Ninh', 9);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('TDD', 'Đại học Thành Đô', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('TDH', 'Đại học Sư Phạm Thể Dục Thể Thao Hà Nội', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('TDL', 'Đại học Đà Lạt', 32);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('TDM', 'Đại học Thủ Dầu Một', 3);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('TDS', 'Đại học Thể Dục Thể Thao Tphcm', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('TDV', 'Đại học Vinh', 35);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('TGC', 'Học viện Báo Chí - Tuyên Truyền', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('TGH', 'Trường Sĩ quan Tăng Thiết Giáp - Thi Phía Bắc', 55);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('TGS', 'Trường Sĩ quan Tăng Thiết Giáp- Thi Phía Nam', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('THP', 'Đại học Hải Phòng', 23);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('THV', 'Đại học Hùng Vương', 38);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('TLA', 'Đại học Thuỷ Lợi', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('TLS', 'Đại học Thuỷ Lợi (phía Nam)', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('TMA', 'Đại học Thương Mại', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('TSB', 'Đại học Nha Trang - Dự Thi Tại Bắc Ninh', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('TSN', 'Đại học Nha Trang', 25);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('TSS', 'Đại học Nha Trang - Dự Thi Tại Cần Thơ', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('TTB', 'Đại học Tây Bắc', 45);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('TTD', 'Đại học Thể Dục Thể Thao Đà Nẵng', 57);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('TTG', 'Đại học Tiền Giang', 50);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('TTH', 'Trường Sĩ Quan Thông Tin - Phía Bắc', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('TTN', 'Đại học Tây Nguyên', 58);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('TTQ', 'Đại học Quốc Tế Sài Gòn', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('TTS', 'Trường Sĩ Quan Thông Tin - Phía Nam', 25);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('TTU', 'Đại học Tân Tạo', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('TYS', 'Đại học Y Khoa Phạm Ngọc Thạch', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('VGU', 'Đại học Việt Đức', 3);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('VHD', 'Đại học Công Nghiệp Việt - Hung', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('VHH', 'Đại học Văn Hoá Hà Nội', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('VHS', 'Đại học Văn Hoá Tphcm', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('VPH', 'Trường Sĩ Quan Kỹ Thuật Quân Sự- Vin-hem-pich- Hệ Quân Sự- Phía Bắc', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('VPS', 'Trường Sĩ Quan Kỹ Thuật Quân Sự- Vin-hem-pich- Hệ Quân Sự- Phía Nam', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('VTT', 'Đại học Võ Trường Toản', 63);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('VUI', 'Đại học Công Nghiệp Việt Trì', 38);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('XDA', 'Đại học Xây Dựng Hà Nội', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('XDT', 'Đại học Xây Dựng Miền Trung', 39);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('YCT', 'Đại học Y Dược Cần Thơ', 13);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('YDD', 'Đại học Điều Dưỡng Nam Định', 34);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('YDS', 'Đại học Y Dược Tphcm', 24);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('YHB', 'Đại học Y Hà Nội', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('YKV', 'Đại học Y Khoa Vinh', 35);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('YPB', 'Đại học Y Hải Phòng', 23);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('YQH', 'Học viện Quân Y - Phía Bắc', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('YQS', 'Học viện Quân Y - Phía Nam', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('YTB', 'Đại học Y Thái Bình', 47);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('YTC', 'Đại học Y Tế Công Cộng', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('ZCH', 'Trường Sĩ Quan Công Binh Hệ Dân Sự', 3);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('ZNH', 'Đại học Văn Hoá - Nghệ Thuật Quân Đội - Phía Bắc', 17);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('ZNS', 'Đại học Văn Hoá - Nghệ Thuật Quân Đội - Phía Nam', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('ZPH', 'Đại học Trần Đại Nghĩa', 0);
INSERT INTO "Entrance_Scores"."collegeEntities" (code, name, province_id) VALUES ('ZTH', 'Trường Sĩ Quan Thông Tin', 0);