// <auto-generated />
using Crawl_College_Entrance_Scores;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Crawl_College_Entrance_Scores.Migrations
{
    [DbContext(typeof(EntranceScoresContext))]
    partial class EntranceScoresContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Entrance_Scores")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Crawl_College_Entrance_Scores.entity.CollegeEntity", b =>
                {
                    b.Property<string>("code")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.Property<long>("province_id");

                    b.HasKey("code");

                    b.HasIndex("province_id");

                    b.ToTable("collegeEntities");
                });

            modelBuilder.Entity("Crawl_College_Entrance_Scores.entity.MajorCollege", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CollegeEntityId");

                    b.Property<string>("MajorEntityId");

                    b.Property<string>("groupCode");

                    b.Property<double>("score");

                    b.Property<int>("year");

                    b.HasKey("id");

                    b.HasIndex("CollegeEntityId");

                    b.HasIndex("MajorEntityId");

                    b.ToTable("majorColleges");
                });

            modelBuilder.Entity("Crawl_College_Entrance_Scores.entity.MajorEntity", b =>
                {
                    b.Property<string>("code")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.HasKey("code");

                    b.ToTable("majorEntities");
                });

            modelBuilder.Entity("Crawl_College_Entrance_Scores.entity.Province", b =>
                {
                    b.Property<long>("province_id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.HasKey("province_id");

                    b.ToTable("provinces");
                });

            modelBuilder.Entity("Crawl_College_Entrance_Scores.entity.CollegeEntity", b =>
                {
                    b.HasOne("Crawl_College_Entrance_Scores.entity.Province", "province")
                        .WithMany("collegeEntities")
                        .HasForeignKey("province_id")
                        .HasConstraintName("ForeignKey_Province_CollegeEntity")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Crawl_College_Entrance_Scores.entity.MajorCollege", b =>
                {
                    b.HasOne("Crawl_College_Entrance_Scores.entity.CollegeEntity", "CollegeEntity")
                        .WithMany("MajorColleges")
                        .HasForeignKey("CollegeEntityId");

                    b.HasOne("Crawl_College_Entrance_Scores.entity.MajorEntity", "MajorEntity")
                        .WithMany("MajorColleges")
                        .HasForeignKey("MajorEntityId");
                });
#pragma warning restore 612, 618
        }
    }
}
